### ISSUE TITLE
Navigation Issues

### ISSUE THREAD

**Issue by thammanvikas** [thammanvikas/construviakrafts#4]
Navigation to/from homepage should work seem-less.

Provide appropriate linkes in html so navigation should work.

**Comment by kamranlatifch** [comment]
You can use anchor (<a>) tags with appropriate href attributes. Here's an example structure.

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
</head>
<body>
    <header>
        <h1>Welcome to My Website</h1>
        <nav>
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/about">About Us</a></li>
                <li><a href="/products">Products</a></li>
                <li><a href="/contact">Contact</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <h2>Homepage Content Goes Here</h2>
        <p>This is the homepage of our website.</p>
    </main>

    <footer>
        <p>&copy; 2024 Your Website</p>
    </footer>
</body>
</html>
